#config.py
duration=15
TIME_BETWEEN_MESSAGES=5
CHAT_MESSAGES=['Present']
ZOOM_MEETING_PASSWORD = "RStEWmdLL2VRMXNid0gyRDVZz09"
ZOOM_MEETING_LINK = "81880992041"
BOT_NAMES=["Reda","Saad","Batbot","Alaa"]